coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      go:
        target: 80%
        threshold: 1%
        flags:
          - go
        paths:
          - "engine/"
      frontend:
        target: 80%
        threshold: 1%
        flags:
          - frontend
        paths:
          - "gui/frontend/src/"
    patch:
      default:
        target: 80%
        threshold: 1%

flags:
  go:
    paths:
      - engine/
    carryforward: false
  frontend:
    paths:
      - gui/frontend/src/
    carryforward: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "cli/**"
  - "node-runner/**"
  - "docs/**"
  - "gui/frontend/src/test/**"
