// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: history.sql

package db

import (
	"context"
)

const clearHistory = `-- name: ClearHistory :exec
DELETE FROM history
`

func (q *Queries) ClearHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearHistory)
	return err
}

const deleteHistoryEntry = `-- name: DeleteHistoryEntry :exec
DELETE FROM history WHERE id = ?
`

func (q *Queries) DeleteHistoryEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteHistoryEntry, id)
	return err
}

const getHistory = `-- name: GetHistory :one
SELECT id, timestamp, request, response, duration_ms
FROM history
WHERE id = ?
`

func (q *Queries) GetHistory(ctx context.Context, id string) (History, error) {
	row := q.db.QueryRowContext(ctx, getHistory, id)
	var i History
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Request,
		&i.Response,
		&i.DurationMs,
	)
	return i, err
}

const insertHistory = `-- name: InsertHistory :exec
INSERT INTO history (id, timestamp, request, response, duration_ms)
VALUES (?, ?, ?, ?, ?)
`

type InsertHistoryParams struct {
	ID         string `json:"id"`
	Timestamp  int64  `json:"timestamp"`
	Request    string `json:"request"`
	Response   string `json:"response"`
	DurationMs int64  `json:"duration_ms"`
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertHistory,
		arg.ID,
		arg.Timestamp,
		arg.Request,
		arg.Response,
		arg.DurationMs,
	)
	return err
}

const listHistory = `-- name: ListHistory :many
SELECT id, timestamp, request, response, duration_ms
FROM history
ORDER BY timestamp DESC
LIMIT ? OFFSET ?
`

type ListHistoryParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Request,
			&i.Response,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
