// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type History struct {
	ID         string `json:"id"`
	Timestamp  int64  `json:"timestamp"`
	Request    string `json:"request"`
	Response   string `json:"response"`
	DurationMs int64  `json:"duration_ms"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
